name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/nginx-html:latest

    - name: Get Jenkins crumb
      run: |
        CRUMB=$(curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')
        echo "CRUMB=$CRUMB" >> $GITHUB_ENV
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        
    - name: Trigger Jenkins build
      run: |
        echo "URL: http://${{ secrets.JENKINS_URL }}/job/GithubProject/build?token=${{ secrets.JENKINS_TOKEN }}"
        curl -L -X POST -H "Jenkins-Crumb:$CRUMB" "https://${{ secrets.JENKINS_URL }}/job/GithubProject/build?token=${{ secrets.JENKINS_TOKEN }}"
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
