name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/nginx-html:latest

    - name: Trigger Jenkins build
      run: |
        echo "URL: http://${{ secrets.JENKINS_URL }}/job/GithubProject/build?token=${{ secrets.JENKINS_TOKEN }}"
        curl -v -X POST -H "Jenkins-Crumb:${{ secrets.CRUMB }}" "${{ secrets.JENKINS_URL }}/job/GithubProject/build?token=${{ secrets.JENKINS_TOKEN }}"
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        CRUMB: ${{ secrets.CRUMB }}
